name: car_wash_app
description: A mobile car wash booking app.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.10.0
  firebase_messaging: ^14.7.10
  provider: ^6.1.2
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.1
  flutter_local_notifications: ^16.1.0
  pdf: ^3.10.1
  intl: ^0.19.0
  image_picker: ^1.0.8
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/
    - assets/animations/